version: 2.1
orbs: 
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.1.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Install Front-End Dependencies
          command: |
            npm run frontend:install
      - run:
          name: Install Back-End Dependencies
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test
      - run:
          name: Back-End Test
          command: |
            npm run backend:Test
      - run:
          name: Deploy App Front-End
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy App Back-End
          command: |
            npm run backend:deploy
workflows:
    Udagram:
      jobs:
        - build:
            filters:
              branches:
                only:
                  - main